### PR TITLE
Disable set_python_home on Windows

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Re kicked the appveyor tests, although it seems that the tests run forever.

```
[ RUN      ] debugger.init
```

**Comment by SylvainCorlay** [comment]
Closing as it seems to be breaking tests, and in fact, binary replacement has been re-enabled on windows:

https://github.com/conda/conda/blob/master/docs/source/release-notes.rst#improvements-62

sorry for recommending the wrong fix.

**Comment by martinRenou** [comment]
No worries. I wasn't sure how to debug the tests, we wanted to take a look at it with Johan

**Comment by SylvainCorlay** [comment]
I think we need to at why relocation is not done on window. Wr might need
to look at the conda recipe instead.

**Pull request closed without merging**
